#Joystick Settings
device_id: 1

#Sensitivity
sensitivity: 0.5
dead_zone: 2000
movement_dead_zone: 1

#Max Speed
max_speed_enabled: false
max_speed: 1000

#Smooth Reset
smooth_reset_enabled: true
smooth_reset_speed: 500

#Vertical Axis Movement
vertical_movement_enabled: false

#Hotkeys - Example: 'F8', 'F9', or characters like 't'
toggle_hotkey: F8 
exit_hotkey: F9

#Logging
logging_enabled: true
logging_level: INFO  # - Options: DEBUG, INFO, WARNING, ERROR, CRITICAL